### Create User mash
POST http://127.0.0.1:4444/auth/signup
Content-Type: application/json

{
    "email" : "test@email.com",
    "username" : "test-user",
    "name" : "test",
    "password" : "xbEmQ1hoIshz7OVdWxA"
}

### Find User by email
POST http://127.0.0.1:4444/users/
Content-Type: application/json

{
    "email" : "test@email.com"
}